#!/bin/zsh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PACKAGE_RESOLVED="$ROOT_DIR/Mitori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
CHECKOUTS_DIR="$ROOT_DIR/.xcodebuild/community/SourcePackages/checkouts"
MANUAL_LICENSES_DIR="$ROOT_DIR/Resources/AdditionalLicenses"
OUTPUT_PATH="$ROOT_DIR/Mitori/Resources/OpenSourceLicenses.md"

typeset -A MANUAL_LICENSE_OVERRIDES
typeset -A PACKAGE_NAME_MAP
typeset -A MANUAL_CORRECTIONS
MANUAL_LICENSE_OVERRIDES=()
PACKAGE_NAME_MAP=()
MANUAL_CORRECTIONS=()

function with_retry {
    local retries=3
    local attempt=1

    while (( attempt <= retries )); do
        if "$@"; then
            return 0
        fi
        echo "[!] attempt $attempt of $retries failed" >&2
        attempt=$((attempt + 1))
    done
    return 1
}

function resolve_packages {
    xcodebuild -resolvePackageDependencies \
        -project "$ROOT_DIR/Mitori.xcodeproj" \
        -scheme Mitori \
        -derivedDataPath "$ROOT_DIR/.xcodebuild/community" 2>&1 | \
        xcbeautify --disable-colored-output --disable-logging
}

if ! command -v xcbeautify >/dev/null 2>&1; then
    echo "[!] xcbeautify is required. Install it with: brew install xcbeautify" >&2
    exit 69
fi

if ! command -v npm >/dev/null 2>&1; then
    echo "[!] npm is required. Install Node.js with: brew install node" >&2
    exit 69
fi

echo "[*] installing locked formatter..."
(
    cd "$ROOT_DIR"
    npm ci --ignore-scripts --no-audit --no-fund
)

echo "[*] resolving packages..."
with_retry resolve_packages

if [[ ! -d "$CHECKOUTS_DIR" ]]; then
    echo "[!] Swift package checkouts are missing after dependency resolution." >&2
    exit 1
fi

if [[ -f "$PACKAGE_RESOLVED" ]]; then
    identity=""
    while IFS= read -r line; do
        if [[ "$line" == *'"identity" : "'* ]]; then
            identity="${line#*\"identity\" : \"}"
            identity="${identity%%\"*}"
        elif [[ -n "$identity" && "$line" == *'"location" : "'* ]]; then
            location="${line#*\"location\" : \"}"
            location="${location%%\"*}"
            repository_name="${location##*/}"
            repository_name="${repository_name%.git}"
            PACKAGE_NAME_MAP[$identity]="${MANUAL_CORRECTIONS[$identity]-$repository_name}"
            identity=""
        fi
    done < "$PACKAGE_RESOLVED"
fi

TEMP_PATH="$(mktemp "${TMPDIR:-/tmp}/mitori-licenses.XXXXXX")"
trap 'rm -f "$TEMP_PATH"' EXIT

print '# Open Source Licenses\n' > "$TEMP_PATH"
print 'Mitori includes the following open-source software. This file is generated by `scripts/scan.license.sh`.\n' >> "$TEMP_PATH"

function package_name_for_directory {
    local directory_name="$(basename "$1")"
    local identity="${directory_name:l}"
    print "${PACKAGE_NAME_MAP[$identity]-$directory_name}"
}

function append_license {
    local package_directory="$1"
    local license_file="$2"
    local source_kind="$3"
    local identity="${$(basename "$package_directory"):l}"
    local package_name="$(package_name_for_directory "$package_directory")"

    if [[ "$source_kind" == "manual" ]]; then
        MANUAL_LICENSE_OVERRIDES[$identity]=1
    elif [[ -n "${MANUAL_LICENSE_OVERRIDES[$identity]-}" ]]; then
        echo "[*] skipping bundled license for $package_name; a manual override exists"
        return
    fi

    print "## $package_name\n" >> "$TEMP_PATH"
    cat "$license_file" >> "$TEMP_PATH"
    print '\n' >> "$TEMP_PATH"

    notice_files=("$package_directory"/NOTICE*(.N))
    for notice_file in "${notice_files[@]}"; do
        print '### Notice\n' >> "$TEMP_PATH"
        cat "$notice_file" >> "$TEMP_PATH"
        print '\n' >> "$TEMP_PATH"
    done
}

echo "[*] scanning licenses..."
package_count=0

while IFS= read -r package_directory; do
    license_files=("$package_directory"/LICENSE*(.N) "$package_directory"/COPYING*(.N))
    if (( ${#license_files} == 0 )); then
        echo "[!] no license found for manual override $(basename "$package_directory")." >&2
        exit 1
    fi
    append_license "$package_directory" "$license_files[1]" manual
done < <(find "$MANUAL_LICENSES_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | LC_ALL=C sort -f)

while IFS= read -r package_directory; do
    identity="${$(basename "$package_directory"):l}"
    if [[ -z "${PACKAGE_NAME_MAP[$identity]-}" ]]; then
        echo "[*] skipping unresolved checkout $(basename "$package_directory")"
        continue
    fi
    license_files=("$package_directory"/LICENSE*(.N) "$package_directory"/COPYING*(.N))
    if (( ${#license_files} == 0 )); then
        echo "[!] no top-level license found for $(basename "$package_directory")." >&2
        exit 1
    fi
    append_license "$package_directory" "$license_files[1]" scanned
    package_count=$((package_count + 1))
done < <(find "$CHECKOUTS_DIR" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort -f)

if (( package_count == 0 )); then
    echo "[!] no Swift package licenses were found." >&2
    exit 1
fi

if grep -Eiq 'GNU (Affero )?(Lesser )?General Public License' "$TEMP_PATH"; then
    echo "[!] a GPL-family license requires manual review." >&2
    exit 1
fi

mv "$TEMP_PATH" "$OUTPUT_PATH"
trap - EXIT

echo "[*] formatting license file with prettier..."
"$ROOT_DIR/node_modules/.bin/prettier" --write "$OUTPUT_PATH"
echo "[*] wrote $OUTPUT_PATH"
